### PR TITLE
fix(VLIW): implement missing ALU instructions

### LINKED ISSUE #163: Problemas con la instrucción SUB de la máquina VLIW
Buenos días, nos hemos encontrado un grave problema en nuestra ejecución de VLIW y es que el programa no traga la operación SUB, en el momento de esa instrucción la máquina se queda colgada y no sigue. En cambio si cambiamos el sub por otra operación si que funciona a la perfección.
Un saludo

### PR DESCRIPTION
**Pull request by endes0**
This PR fixes the execution of ALU instructions, apart from ADD and ADDi it seems that the rest of instructions were never ported to the VLIW machine. For the fix, I refactored the runOperation to look more similar to the Superescalar implementation, which doesn't use a problematic switch case for opcodes (see #71).  Also, I ported the `shift` functional test to the VLIW, so more type of instructions are tested to avoid having the same issue in the future (Is this regression testing?).

Closes #163

### CODE REVIEW

File: src/test/functional/code/despl.ts [hunk 1]
```diff
@@ -10,4 +10,14 @@ AND  R8 R5 R6
...
+2  0 0 0 0  1 0 1 0
+0
+2  2 0 0 0  3 0 1 0
+2  4 0 0 0  5 0 1 0
+0
+2  5 0 0 0  6 0 1 0
+2  7 0 0 0  8 0 1 0
+1  9 0 0 0`.trim();
+
 export const resultContent = [3, 2, 12, 0, 11, 6, 15, 2, -16, 13];
```
Comment (oxcabe) [inline src/test/functional/code/despl.ts:23]: Add a newline at the end of this file!

**Review by oxcabe — CHANGES_REQUESTED** [review]
LGTM, just the nit with the newline and we're good to go

**Review by oxcabe — APPROVED** [review]

File: src/test/functional/code/despl.ts (hunk 1 above)
Comment (endes0) [reply src/test/functional/code/despl.ts]: Ups, It always happens to me that I forgot at least one file for Biome
